version: '3.8'

services:
  web:
    build: .
    command: [ "gunicorn", "root.wsgi:application", "--bind", "0.0.0.0:8000" ]
    expose:
      - 8000
    ports:
      - ${APP_PORT:-0}:8000
    env_file:
      - .env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/code/static
      - media_volume:/home/app/code/media
    deploy:
      replicas: 2

  db:
    image: postgres:alpine3.17
    container_name: postgres_db
    env_file:
      - .env.prod.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M
#  nginx:
#    build: ./nginx
#    container_name: nginx
#    ports:
#      - "1337:80"
#    depends_on:
#      - web
#    volumes:
#      - ./static:/home/app/code/static
  hp:
    build: ./haproxy
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - web


volumes:
  static_volume:
  media_volume:
  pgdata: